"""add ip and mac to logs content

Revision ID: 078ced15c6ac
Revises: 248394e20586
Create Date: 2025-04-04 10:59:20.019333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078ced15c6ac'
down_revision = '248394e20586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
