"""add ip and mac to logs status

Revision ID: 7fda0dfea93c
Revises: 078ced15c6ac
Create Date: 2025-04-04 12:06:27.930535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fda0dfea93c'
down_revision = '078ced15c6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_code', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.drop_column('status_code')

    # ### end Alembic commands ###
