"""add behavior_note to students

Revision ID: add_behavior_note_to_students
Revises: b3fd972b24ff
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_behavior_note_to_students'
down_revision = 'b3fd972b24ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('behavior_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'behavior_note')
    # ### end Alembic commands ###
