"""add is has excuse

Revision ID: b3fd972b24ff
Revises: 7fda0dfea93c
Create Date: 2025-04-20 19:30:42.624348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3fd972b24ff'
down_revision = '7fda0dfea93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_has_exuse', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('is_has_exuse')

    # ### end Alembic commands ###
