"""Initijss45l444

Revision ID: d779c673e6ea
Revises: 6c3bece59eb9
Create Date: 2025-02-11 06:30:58.075479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd779c673e6ea'
down_revision = '6c3bece59eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_late', sa.Boolean(), nullable=False))

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('job_name')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('is_late')

    # ### end Alembic commands ###
